name: Prepare new release

on:
  workflow_dispatch:
    inputs:
      serverBump:
        description: "Bump server version"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - minor
          - patch
      mobileBump:
        description: "Bump mobile build number"
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-root
  cancel-in-progress: true

jobs:
  bump_version:
    runs-on: ubuntu-latest

    outputs:
      ref: ${{ steps.push-tag.outputs.commit_long_sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_RELEASE_TOKEN }}

      - name: Bump version
        run: misc/release/pump-version.sh -s "${{ inputs.serverBump }}" -m "${{ inputs.mobileBump }}"

      - name: Commit and tag
        id: push-tag
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ttmx
          author_email: git@tteles.dev
          default_author: user_info 
          message: "Version ${{ env.GIRA_VERSION }}"
          tag: ${{ env.GIRA_VERSION }}
          push: true

  build_mobile:
    uses: ./.github/workflows/build-mobile.yml
    needs: bump_version
    secrets: inherit
    with:
      ref: ${{ needs.bump_version.outputs.ref }}

  prepare_release:
    runs-on: ubuntu-latest
    needs: build_mobile

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_RELEASE_TOKEN }}

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk-signed

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.GIRA_VERSION }}
          files: |
            *.apk
          token: ${{ secrets.ORG_RELEASE_TOKEN }}